// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLIc7aMGji9UfQaN2QIwhpbwlmvN3Nu6M',
    appId: '1:193338624164:web:77e6d1f76379505638fe31',
    messagingSenderId: '193338624164',
    projectId: 'waste-food-management-7425e',
    authDomain: 'waste-food-management-7425e.firebaseapp.com',
    databaseURL: 'https://waste-food-management-7425e-default-rtdb.firebaseio.com',
    storageBucket: 'waste-food-management-7425e.firebasestorage.app',
    measurementId: 'G-0N20J4KFKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsjuWL3UiXrV17D_qnuLS4dbBhQEdMRZU',
    appId: '1:193338624164:android:532b21ccaed786ef38fe31',
    messagingSenderId: '193338624164',
    projectId: 'waste-food-management-7425e',
    databaseURL: 'https://waste-food-management-7425e-default-rtdb.firebaseio.com',
    storageBucket: 'waste-food-management-7425e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhJAeKWBy8XwxEHFvdnUuj_lHseoZyDEk',
    appId: '1:193338624164:ios:5526e0534b4ccddd38fe31',
    messagingSenderId: '193338624164',
    projectId: 'waste-food-management-7425e',
    databaseURL: 'https://waste-food-management-7425e-default-rtdb.firebaseio.com',
    storageBucket: 'waste-food-management-7425e.firebasestorage.app',
    iosBundleId: 'com.example.wasteFoodManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhJAeKWBy8XwxEHFvdnUuj_lHseoZyDEk',
    appId: '1:193338624164:ios:5526e0534b4ccddd38fe31',
    messagingSenderId: '193338624164',
    projectId: 'waste-food-management-7425e',
    databaseURL: 'https://waste-food-management-7425e-default-rtdb.firebaseio.com',
    storageBucket: 'waste-food-management-7425e.firebasestorage.app',
    iosBundleId: 'com.example.wasteFoodManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLIc7aMGji9UfQaN2QIwhpbwlmvN3Nu6M',
    appId: '1:193338624164:web:5b4d39f9c4e83acb38fe31',
    messagingSenderId: '193338624164',
    projectId: 'waste-food-management-7425e',
    authDomain: 'waste-food-management-7425e.firebaseapp.com',
    databaseURL: 'https://waste-food-management-7425e-default-rtdb.firebaseio.com',
    storageBucket: 'waste-food-management-7425e.firebasestorage.app',
    measurementId: 'G-TKT2ZJ5RM2',
  );

}